### ISSUE TITLE
better uwuify api

### ISSUE THREAD

**Issue by Daniel-Liu-c0deb0t** [Olaren15/uwu-tray#2]
i made a new release `uwuify = 0.2.0` that has a better api, and included more info in the [docs](https://docs.rs/uwuify/latest/uwuifier/) on calling `uwuify_sse`. hopefully this would be easier to use for you :)

**Comment by Olaren15** [comment]
I updated the crate to 0.2.1 in commit ee702c30876f2a713fe8d720bf9de2e7884e7d22
