### ISSUE TITLE
Clicked on uwu-tray.exe... nothing happen

### ISSUE THREAD

**Issue by dawnFirefly** [Olaren15/uwu-tray#4]
So I download both uwu-tray.exe and uwu-tray, but nothing happen when I clicked on it. No icon show up in system tray or notification, checked Task Manager program is not running, my text in clipboard did not turns into UwU,am I missing something? 

*_*Sad uwu sound*_*

**Comment by Olaren15** [comment]
Seems like the 0.1.1 windows executable is not working. I'll investigate on that.
The 0.1.0 version seems to be fine though. You can download it [here](https://github.com/Olaren15/uwu-tray/releases/tag/0.1.0) and use that in the meantime

**Comment by dawnFirefly** [comment]
thanks, (ꈍᴗꈍ) vewsion 0.1.0 i-is indeed wowking 

However it seems to uncapitalize every word, I do not think it is good for first word of each sentence and "I".

**Comment by Olaren15** [comment]
I have updated the 0.1.1 release. The windows executable should work fine now
